Update integration-tests.yml

diff --git a/.github/workflows/integration-tests.yml b/.github/workflows/integration-tests.yml
--- a/.github/workflows/integration-tests.yml
+++ b/.github/workflows/integration-tests.yml
@@ -59,18 +59,29 @@ jobs:
         run: |
           DB_DSN=postgres://user_test:pass_test@localhost:5432/pulse_finder_test?sslmode=disable \
           NATS_URL=nats://localhost:4222 \
+          echo "Starting integration tests with DB_DSN=$DB_DSN and NATS_URL=$NATS_URL" && \
+          DB_DSN=postgres://user_test:pass_test@localhost:5432/pulse_finder_test?sslmode=disable \
+          NATS_URL=nats://localhost:4222 \
           make test/integration/no-cache
 
-      - name: Capture PostgreSQL logs if tests fail
-        if: failure()
+      - name: Test Database Connection
+        run: |
+          PGPASSWORD=pass_test psql -h localhost -U user_test -d pulse_finder_test -c '\dt'
+
+      - name: Test NATS Connection
+        run: |
+          curl -s http://localhost:8222/ > /dev/null || echo "Failed to connect to NATS"
+
+      - name: Capture PostgreSQL logs
+        if: always()
         run: docker logs pulse_db_test
 
-      - name: Capture NATS logs if tests fail
-        if: failure()
+      - name: Capture NATS logs
+        if: always()
         run: docker logs pulse_nats_test
 
-      - name: Capture Migration Logs if Tests Fail
-        if: failure()
+      - name: Capture Migration Logs
+        if: always()
         run: docker logs pulse_db_migration_test
 
       - name: Tear down Docker Compose
